# Definitions:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

regions = {
    "USA": "USA",
    "California" : ["CA"],
    "Texas" : ["TX"],
    "Florida" : ["FL"],
    "Southeast" : ["AL", "AR", "GA", "KY", "LA", "MS", "NC", "SC", "TN"],
    "Southwest" : ["AZ", "NM", "NV", "OK", "UT"],
    "Pacific Northwest & Rockies" : ["CO", "ID", "MT", "OR", "WA", "WY", "AK"],
    "Great Plains": ["IA", "KS", "MN", "MO", "ND", "NE", "SD"],
    "Great Lakes": ["IL", "IN", "MI", "OH", "WI"],
    "Mid-Atlantic": ["DC", "DE", "MD", "PA", "VA", "WV"],
    "Northeast": ["CT", "MA", "ME", "NH", "NJ", "NY", "RI", "VT"],
    "Hawaii and Puerto Rico": ["HI", "PR"]
}